USE [master]
GO

/****** Object:  Database [Dolars]    Script Date: 01.05.2018 20:49:11 ******/
CREATE DATABASE [Dolars]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Dolars', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Dolars.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Dolars_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Dolars_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Dolars] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Dolars].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Dolars] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Dolars] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Dolars] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Dolars] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Dolars] SET ARITHABORT OFF 
GO

ALTER DATABASE [Dolars] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Dolars] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Dolars] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Dolars] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Dolars] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Dolars] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Dolars] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Dolars] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Dolars] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Dolars] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Dolars] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Dolars] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Dolars] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Dolars] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Dolars] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Dolars] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Dolars] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Dolars] SET RECOVERY FULL 
GO

ALTER DATABASE [Dolars] SET  MULTI_USER 
GO

ALTER DATABASE [Dolars] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Dolars] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Dolars] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Dolars] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Dolars] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Dolars] SET QUERY_STORE = OFF
GO

USE [Dolars]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Dolars] SET  READ_WRITE 
GO

